### ISSUE TITLE
Feature request: OpenID Connect authentication

### ISSUE THREAD

**Issue by renne** [nextcloud/integration_paperless#22]
Paperless-ngx supports OpenID-Connect authentication.
In conjunction with the Nextcloud plugin [OIDC Identity Provider](https://apps.nextcloud.com/apps/oidc) the setup is quite simple:

1. Install and enable Nextcloud plugin [OIDC Identity Provider](https://apps.nextcloud.com/apps/oidc)
1. Add new OpenID Connect-Client in `https://nextcloud.example.com/settings/admin/security`
    1. Name = `Paperless-ngx`
    1. Redirect-URI = `https://paperless.example.com`
    1. Copy ClientID and secret
1. In the Paperless-ngx `docker-compose.yml` add environmnet variables for service `webservice:`
```yaml
PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect": {"APPS": [{"provider_id": "nextcloud","name": "Nextcloud","client_id": "<Nextcloud client ID>","secret": "<Nextcloud client secret>","settings": { "server_url": "https://nextcloud.example.com"}}]}}'
PAPERLESS_DISABLE_REGULAR_LOGIN: true
```
